# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
name: ${APP_NAME:-scheduler-web}

services:
  app:
    image: scheduler-web
    build:
      context: .
      args:
        - VERSION=dev
      platforms:
        - linux/amd64
        - linux/arm64
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run dev
    environment:
      - NODE_ENV=development # production || development
      # api-config
      - API_URL=http://host.docker.internal:8000/api/

      # local saml-config
      - APP_URL=http://localhost:9000/
      - SAML_IDENTITY_PROVIDER_URL=http://localhost:9090/simplesaml/saml2/idp/SSOService.php
      - SAML_ISSUER=localhost
      - SAML_IDP_CERT=./saml/simplesamlphp_idp.crt
      # auth-signing-key
      - JWT_AUTH_SIGNING_KEY=insecureT0kenSigningKey

      # simplesaml-config
      - TZ=America/Vancouver

    volumes:
      - ./:/app
    ports:
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9000 || exit 1" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - openlab-scheduler-network

  idp:
    image: kenchan0130/simplesamlphp
    ports:
      - "9090:8080"
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=localhost
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost:9000/auth/login/callback
      - SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=http://localhost:9000/auth/logout/callback
    volumes:
      - ./saml/authsources.php:/var/www/simplesamlphp/config/authsources.php

      # mount saml-idp-certificate
      - ./saml/simplesamlphp_idp.crt:/var/www/simplesamlphp/config/idp.crt
    networks:
      - openlab-scheduler-network

  # jsdocs:
  #   image: node:21-alpine
  #   command:
  #     - /bin/sh
  #     - -c
  #     - |
  #       ./node_modules/.bin/jsdoc -c ./jsdoc.conf.json -r
  #   working_dir: /build
  #   volumes:
  #     - .:/build

networks:
  openlab-scheduler-network:
